version: '3'

services:

  # # Create frontend container
  # blast-off-frontend: # Name of our service
    # build: ./blast-off-frontend
    # ports: # Port binding to host from docker container
      # - "3000:3000"
    # container_name: blast-off-frontend
    # restart: always
    # links:
      # - blast-off-backend
      
  # # Create backend container
  # blast-off-backend:
    # # Create backend container  
    # build: ./blast-off-backend
    # ports:
      # - "8000:8000"
    # container_name: blast-off-backend
    # restart: always
    # links:
      # - blast-off-db
      
  # Create database container
  blast-off-db:
   container_name: blast-off-db
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: blast-off-db
     MYSQL_USER: user
     MYSQL_PASSWORD: password
    